### ISSUE TITLE
Remove useless informations in json files

### ISSUE THREAD

**Issue by nicolasdalsass** [nicolasdalsass/feheroes#2]
Right now, each hero has 30 associated numbers per level. Of these 30, 6 are useful, and the 24 others are computer computable, which should be done to reduce human input time and errors.

**Comment by laicar** [comment]
Which ones are the relevant numbers? Some level 40 stats are +/- 4 instead of +/-3.

**Comment by nicolasdalsass** [comment]
Yes, but we can predict which are +4/-4 instead of +/-3 based on the difference between level 1 and level 40 values ! As explained here : http://feheroes.gamepedia.com/Stat_Growth#Stat_Variation
